### ISSUE TITLE
[1.27.0] runFlow does not expand relative path when used with `../someFile.yaml`

### ISSUE THREAD

**Issue by amit-jha-cmd** [mobile-dev-inc/maestro#1059]
**Describe the bug**
`runFlow` command does not expand the relative path when used with `../`. I have all my common utils that can be used across subflows and their subflows but I want to keep all the common utils in one place. 

**To Reproduce**

File structure

```
job/
  checklist/
    happy_checklist.yaml
  verify_vehicle/
    tire_size.yaml
common/
  location_permission.yaml
```

Now, in `checklist.yaml`

```
- runFlow:
    when:
      visible: "Location permission request"
    file: ../../common/location_permission.yaml
```

1. Start the simulator
2. Run `maestro test maestro/job/checklist/checklist.yaml`
3. The Flow fails with 
```
Flow file is invalid: /Users/ajha/Documents/wrench/apps/unified_app/maestro/job/checklist/../../common/launch_app.yaml
```

**Expected behavior**
The path should expand to 
```
/Users/ajha/Documents/wrench/apps/unified_app/maestro/common/launch_app.yaml
```

**Environment information**

- Maestro version: 1.27.0
- Platform: iOS 16.4.0
- Device model and OS version: iPhone 14 Pro
- Simulator
- Host: Mac M1

**Comment by axelniklasson** [comment]
@amit-jha-cmd this is failing due to maestro only considering `maestro/job/checklist/checklist.yaml` to be the source of flow files. Is you instead run `maestro test maestro` and filter the flows you want to use using the [inclusion patterns or tags](https://maestro.mobile.dev/cli/test-suites-and-reports#controlling-what-tests-to-include), that should work for you.
