### ISSUE TITLE
Maestro 1.29.0 - WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)

### ISSUE THREAD

**Issue by Freire71** [mobile-dev-inc/maestro#1219]
**Describe the bug**
During CI execution, I receive the following message: ```WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)```.
I suppose this warning is causing my test execution to be very slow. When I watch the video output, it is very laggy, and it seems to be running with a very low framerate. The low framerate seems to affect my tests, increasing flakiness. I'm running the suite using a production build of my app (which could improve the both app's and e2e performance)
I'm using CircleCI and tried running with M1 and Intel machines. The problem is not detected locally (I have a M1 Pro with 16gb of ram)

**To Reproduce**
Steps to reproduce the behavior, e.g.:
I'm running the following command in CircleCI
```
echo "Launching iOS Simulator"
xcrun simctl boot "iPhone 14"

echo "Installing app on Simulator"
xcrun simctl install booted <path_to_my_app>

echo "Start video record"
xcrun simctl io booted recordVideo video_record.mp4 & echo $! > video_record.pid

echo "Running tests with Maestro"
$HOME/.maestro/bin/maestro test <path_to_my_flow> \
--format junit
```

**Expected behavior**
- I expect that my video output runs smooth, with a consistent framerate 

**Environment information (please complete the following information):**

- Maestro version 1.29.0
- Platform: iOS 16
- Framework: React Native
- Device model and OS version: Simulator - Iphone 14
- Running in a Simulator
- Host: M1 and Intel

**Comment by igorsmotto** [comment]
Hey @Freire71! This looks to be a problem with your setup, not with Maestro, as such I'm closing this issue.

From the provided error message `WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)` it seems to be a warning related to your Graphics Library being emulated/virtualized in software, and not a real physical GPU (the hardware). 

Since the simulator uses graphics heavily I suspect that by using something virtualized like this the Simulator, and consequently your App it will run extremely slow, even more with a screen recording in place.

As such, I don't believe we can help here, my suggestion is that you avoid using a virtualized MacOS for running the simulator, or if you still want to use the virtualized MacOS, it should have a GPU pinned to it (which kinda makes the virtualization a bit pointless).
