### ISSUE TITLE
[1.30.4] Error when running a directory of tests

### ISSUE THREAD

**Issue by danielbyondd** [mobile-dev-inc/maestro#1308]
**Describe the bug**
Getting a test error when attempting to run a folder of tests. 

**To Reproduce**
`maestro test <folder name>`

**Expected behavior**
Tests will run sequentially

**Screenshots**
![Screenshot 2023-08-01 at 7 16 20 PM](https://github.com/mobile-dev-inc/maestro/assets/107497437/aba6bcb4-82cf-4608-88ee-58b8f3188e0e)

**Environment information (please complete the following information):**

- Maestro version: 1.30.4
- Platform: iOS 16.4
- Framework: iOS 16.4
- Device model and OS version: iPhone 14 Pro Max
- Simulator
- Mac M1

**Workspace (if applicable)**
Please reach out in slack and I can share the test folder, don't want to post here

**Bugreport output (if applicable)**
[Archive (1).zip](https://github.com/mobile-dev-inc/maestro/files/12234727/Archive.1.zip)

**Additional context**

**Comment by ArthurSav** [comment]
Thanks for reporting this Daniel, seems that the issue comes from the naming of the flows. In particular, `/` would cause an issue when trying to create files
`name: "HSA/FSA Store page subfeature"`

Temporary Solution:
- Replace "HSA/FSA" with "HSA_FSA" in all your flow names

I have raised a fix which will be released with the next Maestro version https://github.com/mobile-dev-inc/maestro/pull/1313
