### ISSUE TITLE
[QUESTION] Maestro roadmap?

### ISSUE THREAD

**Issue by juannavalonribas** [mobile-dev-inc/maestro#140]
Hello,

I have been trying maestro for a PoC in my company cause the project it seems promising (congratulations). But it seems the project is in an early stage due to the lack o functionality(timeout configuration, grab elements by data-testid(or other attributes), scroll to a specific element, dynamic content etc.

I am interested in seeing how the tool evolves, is there a public roadmap?

Thanks in advance 😄

**Comment by dmitry-zaitsev** [comment]
Thank you for trying out Maestro!

Current version has actually been in use internally at mobile.dev for about half a year and was executed on thousands of runs across multiple high-profile apps. So we would call it a stable release.

Now, as we are publicly exposing it to more users we keep learning about new use cases that we did not think about originally. To answer your question - **our roadmap is primarily dictated by the popularity of reported GitHub issues**. So if you think that something is missing feature-wise, please open a GitHub issue (or comment on an existing one).

> lack o functionality(timeout configuration, grab elements by data-testid(or other attributes), scroll to a specific element, dynamic content etc.

Some of those we will address in the near future:

- Scroll to a specific element
- Dynamic content

Some of those are already available:

- Querying elements by id can be done via `id` parameter: https://maestro.mobile.dev/reference/tap-on-view

Some we are going to defer as much as possible:

- Querying elements by other attributes. By design, Maestro is a black box testing framework. As much as possible, Maestro sees what user sees. Since user does not know types of views, Maestro shouldn't either. Unless community proves us wrong  in the long run.
- Setting custom timeouts. This is a slippery slope which quickly leads to flaky tests. We believe that default timeouts are already quite long (~10 seconds), going beyond that would mean that a real user would have to wait for such a long time. Then again, if we will be given some convincing examples - I will change my mind :)
