### ISSUE TITLE
[Feature Request] Toggle Airplane Mode

### ISSUE THREAD

**Issue by mdethlefs** [mobile-dev-inc/maestro#1443]
**Is your feature request related to a problem? Please describe.**
Our Apps have certain features that only work in airplane mode - like watching downloaded videos etc.
We need a way to toggle the airplane mode on iOS and Android

**Describe the solution you'd like**
Two simple commands would be great:
`- turnAirplanemodeOn`
`- turnAirplanemodeOff`

**Describe alternatives you've considered**
We tried to do this with the settings app and via control center but that solution is very flaky. Especially on different OS versions

**Comment by bartekpacia** [comment]
Looks like it's possible on Android through `adb` ([link](https://stackoverflow.com/questions/10506591/turning-airplane-mode-on-via-adb)).

It'd be a bit problematic on iOS though, because Airplane Mode is only visible in Control Center on physical devices, which are currently unsupported (see #686). Once they are supported, toggling the airplane mode still (likely) wouldn't work through calling a command (like `adb` on Android), because there isn't one. So Maestro would have to click through the UI manually - fortunately the icons in the Control Center have a language-independent identifier assigned:

Once Control Center is opened, airplane mode could be enabled with:

```swift
let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")
let toggle = springboard.switches["airplane-mode-button"]
if toggle.value! as! String == "0" {
  toggle.tap()
}
```

And to open Control Center:

```swift
func openControlCenter() {
  let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")

  let start: CGVector
  let end: CGVector

  if self.isIphone8OrLower() {
    start = CGVector(dx: 0.5, dy: 0.99)
    end = CGVector(dx: 0.5, dy: 0.8)
  } else {
    start = CGVector(dx: 0.9, dy: 0.01)
    end = CGVector(dx: 0.9, dy: 0.2)
  }

  let startCoord = springboard.coordinate(withNormalizedOffset: start)
  let endCoord = springboard.coordinate(withNormalizedOffset: end)
  startCoord.press(forDuration: 0.1, thenDragTo: endCoord)
}
```

**Comment by amar-mindtickle** [comment]
@bartekpacia How would you run adb through maestro test/yaml file?

**Comment by bartekpacia** [comment]
I don't think it's possible now - I was just sketching out implementation idea.

**Comment by bartekpacia** [comment]
Support for configuring airplane mode on Android was implemented in https://github.com/mobile-dev-inc/maestro/pull/1672

And since there's no airplane mode on simulator, I'm going to close this issue.
