### ISSUE TITLE
Issue in testing button inside bottom sheet modal [v.1.3.3]

### ISSUE THREAD

**Issue by Othman2001** [mobile-dev-inc/maestro#1493]
**Describe the bug**
I have an app which uses bottom sheet modal https://github.com/gorhom/react-native-bottom-sheet
I am trying to test a button  rendered inside the bottom sheet (the user clicks on text called "Find out" and then the bottom sheet modal opens that has a button "Getting Started" 
I have added assert for tapOn: - tapOn: "Getting started". but the test fails, i have tried master studio but it can't inspect the bottom sheet it shows the bottom sheet as component and i can't inspect any of it is children

**To Reproduce**
create react native app  
install bottom sheet from npm https://github.com/gorhom/react-native-bottom-sheet
use the bottom sheet in your app and try to inspect any of it is children

- Maestro version [e.g. v1.3.3]
- Platform: [e.g. iOS 15.4.1]
- Framework: [react native]
- Device model and OS version: [Iphone 14 pro max]
- Simulato
- Host [mac m1 ]

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by markholland** [comment]
Same here. Assigning a testID doesn't work either.

**Comment by warcello** [comment]
In my case tapping on text works in following way:
```
- tapOn: 
    text: "someText"
```

However it does not work with an id...

**Comment by beqramo** [comment]
same here too...

**Comment by StefanWallin** [comment]
Same here! I'm thinking it could be that there is just too many items visible on screen because my gorhom bottom sheets is covering a apple maps view with a bunch of pinpoints and named locations on it. The handle of the gorhom bottom sheet is selectable but nothing in it. When I try tapping something in Maestro studio, it only gives me some container view:

<img width="724" alt="Screenshot 2024-02-24 at 17 33 45" src="https://github.com/mobile-dev-inc/maestro/assets/457653/45f8f8df-3e8a-49a0-bdab-bc19eff0e16e">

**Comment by vyobukhov** [comment]
If it will help to find a source of issue:

- the issue is IOS only
- BottomSheetModal is used
- Only "Bottom Sheet" and "Bottom Sheet Handle" are visible to Maestro and can be selected by it's `accessibilityLabel`.
- Everything inside the bottom sheet is not available and not listed in maestro view hierarchy 

Here are two screenshots to compare
| IOS  | Android |
| ------------- | ------------- |
| ![Screenshot 2024-02-27 at 11 27 04](https://github.com/mobile-dev-inc/maestro/assets/1265071/56db5cca-014b-465d-937c-a9c374f587b2) | ![Screenshot 2024-02-27 at 11 25 20](https://github.com/mobile-dev-inc/maestro/assets/1265071/76b12469-35ec-4a4f-96db-4460d889e89f)  |

**Comment by flo-sch** [comment]
This might (my knowledges of accessibility roles being limited to my own experience) be a side-effect of the default attributes introduced by the BottomSheet component in 4.6.0: https://github.com/gorhom/react-native-bottom-sheet/pull/1288/files#diff-5a2db14facf13a3da647cb85a27700e0cddade0c6a5e136428e7e63fea4ac242R39

I believe it can be worked around by overriding `accessible={false}` to the BottomSheet component on iOS, which then allow the children to be read by Voice Over on iOS (at least in my case).
I wonder if the issue comes from the role being set to "adjustable" by default or something else, and there are surely better ways to fix that, but give it a try perhaps?

```tsx
import { Platform } from 'react-native';
import { BottomSheetModal } from '@gorhom/bottom-sheet';

<BottomSheetModal
  accessible={Platform.select({
    // setting it to false on Android seems to cause issues with TalkBack instead
    ios: false
  })}
  // ...
>
  // ...
</BottomSheetModal>
```

**Comment by beqramo** [comment]
@flo-sch that worked. Thank you.

**Comment by flo-sch** [comment]
NOTE: it seems that I am unable to select text components on Android within the modal for some reasons. Digging into that
