### ISSUE TITLE
[1.36.0] Android 14 - SecurityException

### ISSUE THREAD

**Issue by SergeyKornyushin** [mobile-dev-inc/maestro#1803]
Hi.

"As discussed at Google I/O 2023, registering receivers with intention using the RECEIVER_EXPORTED / RECEIVER_NOT_EXPORTED flag was introduced as part of Android 13 and is now a requirement for apps running on Android 14 or higher (U+).
If you do not implement this, the system will throw a security exception."

So i get a SecurityException crash on Android 14 in few test-cases

**To Reproduce**
1. Start non short test-cases (my test contain 3-5 flow) on Android 14 device/emulator.
2. Crash SecurityException

**Expected behavior**
On previous android api (33-) everything works fine

**Screenshots**
![image](https://github.com/user-attachments/assets/21b5422c-ff00-4d4e-9a15-3052d90a7b17)

**Environment information (please complete the following information):**
- Maestro version [1.36.0]
- Platform: [Android 14]
- Framework: [Native Android]
- Device model and OS version: [Clear android]
- Simulator, emulator or physical device - both
- Host [Windows WSL]

**Additional context**
I tried to register broadcast receiver like
```
registerReceiver(
   receiver,
   IntentFilter(Intent.ACTION_ALL_APPS),
   RECEIVER_EXPORTED/RECEIVER_NOT_EXPORTED
)
```
but it's give nothing, maybe i need to set some specific IntentFilter, but which?

**Comment by bartekpacia** [comment]
Hey @SergeyKornyushin,

> To Reproduce
>
> 1. Start non short test-cases (my test contain 3-5 flow) on Android 14 device/emulator.
> 2. Crash SecurityExceptio


This issue is not reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
