### ISSUE TITLE
can't get selector input text otp flutter maestro studio

### ISSUE THREAD

**Issue by fauzisunarya** [mobile-dev-inc/maestro#2048]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

.

### Actual results

Hello, I found a bug where I can't get the selector for OTP input on the Flutter application. How can I input OTP? I have attached the video below.

https://github.com/user-attachments/assets/673cbaf1-e8a3-4c1c-83e5-fdc33db92a48

### Expected results

can input otp

### About app

flutter

### About environment

jdk 21, os wsl

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

latest

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

.

**Comment by bartekpacia** [comment]
You need to make sure that your OTP text field is accessible. Use Flutter's [accessibility/semantics system](https://docs.flutter.dev/ui/accessibility-and-internationalization/accessibility) for this.

Also, this issue is not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
