### ISSUE TITLE
Environment variable not replaced when using `maestro cloud`?

### ISSUE THREAD

**Issue by bitcrumb** [mobile-dev-inc/maestro#456]
Original Slack thread for reference: https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1669976527771819

---

I am trying to dynamically set the `appId` through an environment variable.

Given a minimal flow:
```yaml
appId: ${APP_ID}
---
- launchApp
```

* I get an error when running `maestro cloud app.yaml -e APP_ID=your.app.id` ❌
* However, this is successful when running `maestro test app.yaml -e APP_ID=your.app.id` ✅

The output of the two commands next to each other:

<img width="1001" alt="Screenshot 2022-12-02 at 12 16 34" src="https://user-images.githubusercontent.com/135126/205281159-7fea6b2d-cdef-42cd-8760-4572d2738c9b.png">

**Comment by wcastand** [comment]
Hi, not sure you can apply this to your use case but until they fix it, maybe you can use what i did.

i have subflow that use ${APP_ID} and the main flow (the one launch by maestro cloud or locally) use fixed appId.

the reason it works for me is because i need the appId to be different between local app and prod app.

so i create entry point specific for each but both run the same subflow.

**Comment by ArthurSav** [comment]
Please upgrade to the latest version of Maestro, we have made improvements that should fix this issue. 
If you still experience issues, please open a new issue with reproduction steps.  Thanks again for using Maestro!
