### ISSUE TITLE
SwiftUI ID for view doesn't work

### ISSUE THREAD

**Issue by katovBash** [mobile-dev-inc/maestro#461]
I'm using id, tags for ui in view, but it works incorrectly, it doesn't trigger anything.

Can you show an example please?
Is it working feature on sui?

**Comment by ArthurSav** [comment]
We have made a lot of improvements and fixes since, can you upgrade to the latest version of Maestro and try again? 
Also please checkout our [SwiftUI documentation](https://maestro.mobile.dev/platform-support/ios-swiftui)

If you still experience issues, we can re-open this. 
Thanks again for using Maestro!
