### ISSUE TITLE
[Bug] Maestro unable to find elements, whereas it shows up on idb describe

### ISSUE THREAD

**Issue by denil-ct** [mobile-dev-inc/maestro#727]
Running maestro tests, it is unable to find elements. Sometimes its a tab bar button, other times its just a normal button on a pop up sheet.
Running maestro hierarchy after the test flow has failed, it shows everything as empty
```
{
  "attributes" : { },
  "children" : [ ]
}
```
Running `idb ui describe-all` returns everything on screen including that element, so not sure what is going on.

**Comment by denil-ct** [comment]
On further debugging, we identified it was because of `cellForRowAt` method called endlessly. We try to prefetch rows in our app, but while running maestro the row number jumps to the prefetch trigger limit directly.

For example, let's say we will be triggering the prefetch logic on 4th cell (cells are full screen height elements). In normal app launch, it will get triggered after scrolling to 4th cell. But when the app is getting launched via maestro, the `indexpath.row` property inside the `cellForRowAt` has already jumped to 4, triggering the prefetch logic, which will insert cells on completion, which in turn makes the count jump to 8, again triggering the prefetch logic and it keeps going endlessly.

**Comment by axelniklasson** [comment]
Hi there @denil-ct! Could you try [upgrading to the latest version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) and let us know if this issue still persists? There is a [known issue with UITableView](https://maestro.mobile.dev/troubleshooting/known-issues#ios-issues-with-lists-uicollectionview-uitableview-that-fetch-data-on-scroll) that might offer a workaround if the issue is still there in the latest version. Thanks!

**Comment by denil-ct** [comment]
Seems better now. Thanks.
Closing this issue.
