### ISSUE TITLE
React native support?

### ISSUE THREAD

**Issue by chriscantu** [mobile-dev-inc/maestro#73]
The provided examples only mention iOS and Android.  Given that React native compiles to native components, it should work in theory.   Do you have any guidance for React Native apps?

**Comment by dmitry-zaitsev** [comment]
Good question! Since Maestro relies on accessibility information to function, React Native is supported and works in the same way as any other native app (incl. Flutter, Jetpack Compose, etc.). 

There are no particular differences in integration that we are aware of. To get started, you can look up the view hierarchy of your app by running `maestro hierarcht`
